### ISSUE TITLE
Open thread: how to best load different cores?

### ISSUE THREAD

**Issue by lintool** [castorini/SolrAnserini#2]
Currently, `.docker/load.sh` loads all the cores at once. This is going to become unwieldy for lots of collections.

We should have the ability to selectively load cores? Also, we might want to make this a Python script... because as we add more options, shell scripts are going to becoming more and more annoying.

This might be over-engineering, but perhaps the load script takes in a JSON config that specifies all the cores to load and the index locations?

Another point for discussion - currently, all the cores configs (schema, etc.) are all directly baked into the docker image. Would it make more sense to mount these in the same way as the indexes? We can even have Anserini generate these configs automatically as part of the indexing pipeline - this way, we always ensure that the configs are in sync with the actual indexes.

Thoughts? Open thread for discussion.

**Comment by ryan-clancy** [comment]
We could selectively load cores, but the biggest challenge I see with this is that volumes in Docker (linking host:container directories) are defined when a container is created and can't be added once the container is running. This means that the `docker run` command in `.docker/run.sh` needs to have a `-v host:container` arg for each volume it wishes to mount. We can copy files into a container after the fact, but I don't think this is desirable given the size of some of the indices.

One solution would be to have a `/index/` directory on the root of the container bound to some directory on the host's OS. For example, on `tuna` bind `/tuna1/indexes/` to `/index/` in the Docker image... this is probably preferable to `/core17/`, `/mb13/`, `/mb11/`, etc. Once the index directories are available to the container, we can choose whether or not to actually link them to the proper Solr directory and reload the core.

**Comment by lintool** [comment]
This relates to my suggestion of turning `.docker/run.sh` into a Python script - it would read a config that specifies each core, the config files, and the index, and generate the complex `-v` bindings. Would that work?

**Comment by ryan-clancy** [comment]
Yeah, that seems reasonable - I don't see any issue with that approach.

**Comment by lintool** [comment]
One final tweak, move `run.sh` into top-level directory instead of hiding it inside `.docker/`?

**Comment by lintool** [comment]
Addressed in #3
