### ISSUE TITLE
Snippet Highlighting in Solr

### ISSUE THREAD

**Issue by ryan-clancy** [castorini/SolrAnserini#8]
Currently, snippet highlighting for search terms in Solr doesn't work. This is because we use the `-storeRawDocs` flag, which stores the text in a field called `raw`, but store positions, frequency, etc. in another field called `contents` (which is the field we query on) which only has text stored in it when `-storeTransformedDocs` is passed. The fields are different, so we can't query one but highlight in another.

A few possible solutions are as follows, with minor changes to either Solr or Anserini:

1. Use the Solr `copyField` directive to copy the text from `raw` into `contents` (or vice versa) so highlighting works. This will lead to a larger index, not ideal.
2. Ensure only one of `-storeRawDocs` or `-storeTransformedDocs` are passed when indexing. We then store the positions, frequency, AND text in the same field (either raw or contents) - highlighting will work. This is leaner, but queries would have to change depending on whether we store raw vs. transformed docs (as the field names will differ).
3. Everything goes into the `contents` field and whether we store raw vs. transformed docs depends on `-storeRawDocs` or `-storeTransformedDocs` flag. This is my preferred solution as queries will stay static no matter which kind of docs are stored in the index.

@lintool thoughts?

**Comment by ryan-clancy** [comment]
See https://github.com/castorini/Anserini/pull/480

**Comment by ryan-clancy** [comment]
Highlighting for matches should be done on transformed docs, rather than raw docs, and thus can already be done (in Solr) when the index is built using the `-storeTransformedDocs` flag. It's best to treat things this way rather than duplicating data or changing any code.

See https://github.com/castorini/Anserini/pull/480

**Comment by lintool** [comment]
Note added to Anserini docs in https://github.com/castorini/Anserini/pull/480
